### PR TITLE
SPDX license tags and seL4 Foundation setup

### PR DESCRIPTION
**Pull request by lsf37**

### CODE REVIEW

**Comment by lsf37** [comment]
(will fix up style and links in separate commits to be pushed here)

**Comment by lsf37** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Review by kent-mcleod — APPROVED** [review]

**Comment by lsf37** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Pull request merged**
